proxies:
  - name: "美国-IEPL-G1-1"
    type: vmess
    server: ocean.iepl.mlinuu.top
    port: 3505
    uuid: "92d5e6ca-800a-3fdd-b7f3-b0e902e305cf"
    alterId: 1
    cipher: auto
    network: tcp
    tls: false